/**
 * Adversarial tests generated by /challenge project
 * Targets: rateLimits.ts, incrementalParser.ts, mergeTimeBuckets, pricingEngine.ts
 */

import { subHours, subMinutes } from "date-fns";
import {
	aggregateUsage,
	mergeTimeBuckets,
} from "../../src/aggregation/timeBuckets";
import {
	calculateBurnRateEMA,
	createBurnRateTracker,
} from "../../src/core/burnRate";
import { calculateRateLimits } from "../../src/core/rateLimits";
import type { AggregatedUsage, TimeBuckets, TokenUsage } from "../../src/types";

// ---- Helpers ----

function makeRecord(overrides: Partial<TokenUsage> = {}): TokenUsage {
	return {
		timestamp: new Date(),
		model: "claude-sonnet-4-5",
		sessionId: "test-session",
		inputTokens: 1000,
		outputTokens: 500,
		cacheCreationTokens: 0,
		cacheReadTokens: 0,
		cacheCreation5m: 0,
		cacheCreation1h: 0,
		cost: 0.01,
		...overrides,
	};
}

function emptyBuckets(): TimeBuckets {
	return {
		session: new Map(),
		daily: new Map(),
		weekly: new Map(),
		monthly: new Map(),
		modelWeekly: new Map(),
		hourly: new Map(),
	};
}

function makeAgg(overrides: Partial<AggregatedUsage> = {}): AggregatedUsage {
	return {
		inputTokens: 0,
		outputTokens: 0,
		cacheCreationTokens: 0,
		cacheReadTokens: 0,
		totalCost: 0,
		messageCount: 0,
		firstMessage: null,
		lastMessage: null,
		...overrides,
	};
}

// ==================================================================
// TEST: 5-hour session window over-counts lifetime output tokens
// ==================================================================

describe("calculateRateLimits - 5hr session window", () => {
	it("CRITICAL: should NOT count tokens from messages older than 5 hours in session total", () => {
		const now = new Date();
		const buckets = emptyBuckets();

		// Session that started 8 hours ago, last message 1 hour ago
		// Total lifetime: 100K output tokens
		// Tokens in last 5 hours: ~40K (estimated, but code can't distinguish)
		buckets.session.set(
			"long-session",
			makeAgg({
				outputTokens: 100_000,
				firstMessage: subHours(now, 8),
				lastMessage: subHours(now, 1),
			}),
		);

		const result = calculateRateLimits(buckets, "max5");

		// BUG: The code counts ALL 100K because lastMessage is within 5hrs.
		// Correct behavior: should only count tokens with timestamps in the window.
		// This test documents the bug. It will FAIL with current code:
		expect(result.session5h.currentTokens).toBeLessThan(100_000);
		// Current code returns 100_000 (the full session lifetime)
	});

	it("should correctly count sessions entirely within the 5hr window", () => {
		const now = new Date();
		const buckets = emptyBuckets();

		// Short session, fully within 5hr window
		buckets.session.set(
			"short-session",
			makeAgg({
				outputTokens: 20_000,
				firstMessage: subHours(now, 2),
				lastMessage: subMinutes(now, 30),
			}),
		);

		const result = calculateRateLimits(buckets, "max5");
		expect(result.session5h.currentTokens).toBe(20_000);
	});

	it("should exclude sessions with lastMessage older than 5 hours", () => {
		const now = new Date();
		const buckets = emptyBuckets();

		buckets.session.set(
			"old-session",
			makeAgg({
				outputTokens: 50_000,
				firstMessage: subHours(now, 10),
				lastMessage: subHours(now, 6),
			}),
		);

		const result = calculateRateLimits(buckets, "max5");
		expect(result.session5h.currentTokens).toBe(0);
	});
});

// ==================================================================
// TEST: mergeTimeBuckets should not mutate source operand
// ==================================================================

describe("mergeTimeBuckets - immutability", () => {
	it("CRITICAL: merging should not mutate the first operand's AggregatedUsage values", () => {
		const a = emptyBuckets();
		a.daily.set(
			"2026-03-07",
			makeAgg({ outputTokens: 1000, inputTokens: 500 }),
		);

		const b = emptyBuckets();
		b.daily.set(
			"2026-03-07",
			makeAgg({ outputTokens: 2000, inputTokens: 1000 }),
		);

		// Capture original values
		const originalAOutputTokens = a.daily.get("2026-03-07")!.outputTokens;

		const merged = mergeTimeBuckets(a, b);

		// merged should have combined values
		expect(merged.daily.get("2026-03-07")!.outputTokens).toBe(3000);

		// BUG: a's values should be unchanged, but mergeTimeBuckets mutates them
		// via shallow Map copy + in-place addition
		expect(a.daily.get("2026-03-07")!.outputTokens).toBe(originalAOutputTokens);
		// Current code: a.daily.get("2026-03-07")!.outputTokens === 3000 (mutated!)
	});

	it("should produce independent copies for non-overlapping keys", () => {
		const a = emptyBuckets();
		a.daily.set("2026-03-06", makeAgg({ outputTokens: 500 }));

		const b = emptyBuckets();
		b.daily.set("2026-03-07", makeAgg({ outputTokens: 700 }));

		const merged = mergeTimeBuckets(a, b);

		// Mutate merged - should not affect a
		merged.daily.get("2026-03-06")!.outputTokens = 9999;
		expect(a.daily.get("2026-03-06")!.outputTokens).toBe(500);
	});
});

// ==================================================================
// TEST: CRLF offset calculation
// ==================================================================

describe("incrementalParser - byte offset tracking", () => {
	// This is a design-level test documenting the CRLF bug.
	// The actual incrementalParser reads from disk, so this tests the math.
	it("HIGH: byte offset should account for CRLF (2 bytes) not just LF (1 byte)", () => {
		// Simulate the offset calculation for a CRLF line
		const line =
			'{"type":"assistant","timestamp":"2026-03-07T00:00:00Z","sessionId":"s1","message":{"model":"claude-sonnet-4-5","usage":{"input_tokens":100,"output_tokens":50}}}';
		const lineBytes = Buffer.byteLength(line, "utf8");

		// Current code: bytesRead += lineBytes + 1 (assumes \n)
		const offsetWithLF = lineBytes + 1;

		// Correct for CRLF: bytesRead += lineBytes + 2
		const offsetWithCRLF = lineBytes + 2;

		// The difference accumulates: after 1000 lines, offset is 1000 bytes off
		const linesInFile = 1000;
		const driftAfter1000Lines =
			linesInFile * offsetWithCRLF - linesInFile * offsetWithLF;
		expect(driftAfter1000Lines).toBe(1000);
		// 1000 bytes of drift = starts mid-line on next incremental parse
	});
});

// ==================================================================
// TEST: Pricing engine partial overrides
// ==================================================================

describe("pricingEngine - partial override handling", () => {
	// Note: This test would require mocking vscode.workspace.getConfiguration
	// Documenting the expected behavior:
	it("HIGH: should accept partial pricing overrides merged with defaults", () => {
		// User provides only outputPerMillion override
		const userOverride = { outputPerMillion: 30.0 };

		// Expected: merge with defaults, keeping other fields
		const expected = {
			inputPerMillion: 3.0, // default for sonnet
			outputPerMillion: 30.0, // user override
			cache5mWriteMultiplier: 1.25, // default
			cache1hWriteMultiplier: 2.0, // default
			cacheReadMultiplier: 0.1, // default
		};

		// Current code: ModelPricingSchema.parse(userOverride) throws
		// because inputPerMillion etc. are required.
		// This documents the bug.
		expect(Object.keys(userOverride).length).toBe(1);
		expect(Object.keys(expected).length).toBe(5);
		// The fix: use ModelPricingSchema.partial().parse() then merge with defaults
	});
});

// ==================================================================
// TEST: Utilization normalization edge cases
// ==================================================================

describe("usageApi - parseWindow normalization", () => {
	// parseWindow is not exported, so this documents the logic bug

	it("MEDIUM: utilization of 1.5 (150%) should not be divided by 100", () => {
		// When user exceeds rate limit, API could return utilization > 1.0
		// e.g., 1.5 means 150% of limit
		const rawUtilization = 1.5;

		// Current code: raw.utilization > 1 ? raw.utilization / 100 : raw.utilization
		const currentResult =
			rawUtilization > 1 ? rawUtilization / 100 : rawUtilization;
		expect(currentResult).toBe(0.015); // BUG: shows 1.5% instead of 150%

		// Correct: if API returns fractions (0-1+), use as-is
		// If API returns percentages (0-100+), divide by 100
		// Need to know actual API contract to fix correctly
	});
});

// ==================================================================
// TEST: Burn rate with EMA should handle edge cases
// ==================================================================

describe("calculateBurnRateEMA - edge cases", () => {
	it("should return 0 when no sessions have recent activity", () => {
		const buckets = emptyBuckets();
		buckets.session.set(
			"old",
			makeAgg({
				outputTokens: 50000,
				firstMessage: subHours(new Date(), 10),
				lastMessage: subHours(new Date(), 8),
			}),
		);

		const tracker = createBurnRateTracker();
		const result = calculateBurnRateEMA(buckets, tracker, 15);
		expect(result.rate).toBe(0);
	});

	it("should produce positive rate with active session", () => {
		const now = new Date();
		const buckets = emptyBuckets();
		buckets.session.set(
			"active",
			makeAgg({
				outputTokens: 10000,
				firstMessage: subMinutes(now, 10),
				lastMessage: subMinutes(now, 1),
			}),
		);

		const tracker = createBurnRateTracker();
		const result = calculateBurnRateEMA(buckets, tracker, 15);
		expect(result.rate).toBeGreaterThan(0);
	});

	it("EMA should smooth across multiple calculations", () => {
		const now = new Date();
		const buckets = emptyBuckets();
		buckets.session.set(
			"active",
			makeAgg({
				outputTokens: 10000,
				firstMessage: subMinutes(now, 10),
				lastMessage: subMinutes(now, 1),
			}),
		);

		let tracker = createBurnRateTracker(0.5);
		const result1 = calculateBurnRateEMA(buckets, tracker, 15);
		tracker = result1.tracker;

		// Double the tokens
		buckets.session.get("active")!.outputTokens = 20000;
		const result2 = calculateBurnRateEMA(buckets, tracker, 15);

		// EMA should be between the two raw rates (smoothed)
		expect(result2.rate).toBeGreaterThan(result1.rate);
	});
});

// ==================================================================
// TEST: aggregateUsage correctness
// ==================================================================

describe("aggregateUsage", () => {
	it("should correctly aggregate multiple records into time buckets", () => {
		const records = [
			makeRecord({
				timestamp: new Date("2026-03-07T10:00:00Z"),
				outputTokens: 100,
				sessionId: "s1",
			}),
			makeRecord({
				timestamp: new Date("2026-03-07T11:00:00Z"),
				outputTokens: 200,
				sessionId: "s1",
			}),
			makeRecord({
				timestamp: new Date("2026-03-07T12:00:00Z"),
				outputTokens: 300,
				sessionId: "s2",
			}),
		];

		const buckets = aggregateUsage(records);

		// Session aggregation
		expect(buckets.session.size).toBe(2);
		expect(buckets.session.get("s1")!.outputTokens).toBe(300);
		expect(buckets.session.get("s2")!.outputTokens).toBe(300);
		expect(buckets.session.get("s1")!.messageCount).toBe(2);

		// Daily aggregation
		expect(buckets.daily.size).toBe(1);
		const daily = Array.from(buckets.daily.values())[0];
		expect(daily.outputTokens).toBe(600);
	});

	it("should handle empty records array", () => {
		const buckets = aggregateUsage([]);
		expect(buckets.session.size).toBe(0);
		expect(buckets.daily.size).toBe(0);
	});
});
