/**
 * Adversarial tests for API-first reliability changes
 * Generated by /challenge on 2026-03-15
 * Targets: pollingTimer.ts, usageCache.ts, statusBar.ts, formatting.ts, tierDetection.ts
 */

import { PollingTimer } from "../src/api/pollingTimer";
import { getStaleness } from "../src/api/usageCache";
import { mapTierStringToPlanType } from "../src/core/tierDetection";
import { formatBarGraph, formatPaceForecast } from "../src/ui/formatting";

// Mock logger
const mockLogger = {
	info: jest.fn(),
	warn: jest.fn(),
	error: jest.fn(),
};

describe("PollingTimer", () => {
	beforeEach(() => {
		jest.useFakeTimers();
		jest.clearAllMocks();
	});

	afterEach(() => {
		jest.useRealTimers();
	});

	it("should not start duplicate timer chains on double start()", () => {
		const fetchFn = jest.fn().mockResolvedValue({ fetchedAt: new Date() });
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();
		timer.start(); // idempotent

		jest.advanceTimersByTime(5000);
		expect(fetchFn).toHaveBeenCalledTimes(1); // not 2
		timer.stop();
	});

	it("should not schedule next tick after stop() during fetch", async () => {
		let resolvePromise: (v: any) => void;
		const fetchFn = jest.fn().mockImplementation(
			() =>
				new Promise((r) => {
					resolvePromise = r;
				}),
		);
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();
		jest.advanceTimersByTime(5000); // triggers tick
		expect(fetchFn).toHaveBeenCalledTimes(1);

		// Stop while fetch is in-flight
		timer.stop();

		// Resolve the fetch
		resolvePromise!({ fetchedAt: new Date() });
		await Promise.resolve(); // flush microtasks

		// onData should NOT be called (isRunning guard)
		expect(onData).not.toHaveBeenCalled();
		timer.stop();
	});

	it("should apply exponential backoff on consecutive failures", async () => {
		const fetchFn = jest.fn().mockResolvedValue(null); // null = failure
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();

		// First tick at 5s
		jest.advanceTimersByTime(5000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(1);
		expect(onError).toHaveBeenCalledTimes(1);

		// Second tick at 30s backoff
		jest.advanceTimersByTime(30000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(2);

		// Third tick at 60s backoff
		jest.advanceTimersByTime(60000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(3);

		timer.stop();
	});

	it("should cap backoff at MAX_FAILURE_INTERVAL_MS (300s)", async () => {
		const fetchFn = jest.fn().mockResolvedValue(null);
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();

		// Exhaust through: 5s initial, then 30s, 60s, 120s, 240s, 300s (capped)
		const intervals = [5000, 30000, 60000, 120000, 240000, 300000];
		for (let i = 0; i < intervals.length; i++) {
			jest.advanceTimersByTime(intervals[i]);
			await Promise.resolve();
		}

		// Next interval should still be 300s (capped), not 600s
		jest.advanceTimersByTime(300000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(7);

		timer.stop();
	});

	it("should reset consecutiveFailures on success after failures", async () => {
		let callCount = 0;
		const fetchFn = jest.fn().mockImplementation(() => {
			callCount++;
			return Promise.resolve(callCount >= 3 ? { fetchedAt: new Date() } : null);
		});
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();

		// 5s initial -> fail
		jest.advanceTimersByTime(5000);
		await Promise.resolve();

		// 30s backoff -> fail
		jest.advanceTimersByTime(30000);
		await Promise.resolve();

		// 60s backoff -> success (callCount=3)
		jest.advanceTimersByTime(60000);
		await Promise.resolve();
		expect(onData).toHaveBeenCalledTimes(1);

		timer.stop();
	});

	it("should not throw if onData callback throws", async () => {
		const fetchFn = jest.fn().mockResolvedValue({ fetchedAt: new Date() });
		const onData = jest.fn().mockImplementation(() => {
			throw new Error("callback boom");
		});
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		timer.start();
		jest.advanceTimersByTime(5000);
		await Promise.resolve();

		// Should log error but not crash
		expect(mockLogger.error).toHaveBeenCalled();
		timer.stop();
	});

	it("forceRefresh() should execute tick even without start()", async () => {
		const fetchFn = jest.fn().mockResolvedValue({ fetchedAt: new Date() });
		const onData = jest.fn();
		const onError = jest.fn();
		const timer = new PollingTimer(fetchFn, onData, onError, mockLogger as any);

		// NOTE: This test documents the current behavior (forceRefresh doesn't check isRunning).
		// This is a known issue - forceRefresh should guard against being called when stopped.
		await timer.forceRefresh();
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});
});

describe("getStaleness", () => {
	it("returns 'critical' for null fetchedAt", () => {
		expect(getStaleness(null)).toBe("critical");
	});

	it("returns 'fresh' for recent date", () => {
		const recent = new Date(Date.now() - 60_000); // 1 min ago
		expect(getStaleness(recent)).toBe("fresh");
	});

	it("returns 'normal' for 7 min old date", () => {
		const date = new Date(Date.now() - 7 * 60_000);
		expect(getStaleness(date)).toBe("normal");
	});

	it("returns 'dim' for 15 min old date", () => {
		const date = new Date(Date.now() - 15 * 60_000);
		expect(getStaleness(date)).toBe("dim");
	});

	it("returns 'stale' for 25 min old date", () => {
		const date = new Date(Date.now() - 25 * 60_000);
		expect(getStaleness(date)).toBe("stale");
	});

	it("returns 'critical' for 35 min old date", () => {
		const date = new Date(Date.now() - 35 * 60_000);
		expect(getStaleness(date)).toBe("critical");
	});

	it("returns 'critical' for Invalid Date (NaN propagation)", () => {
		// Invalid Date has NaN getTime(), all comparisons return false, falls to critical
		const invalid = new Date("not-a-date");
		expect(getStaleness(invalid)).toBe("critical");
	});

	it("returns 'critical' for epoch date (Date(0))", () => {
		const epoch = new Date(0);
		expect(getStaleness(epoch)).toBe("critical");
	});
});

describe("mapTierStringToPlanType", () => {
	it("maps max_20 variants", () => {
		expect(mapTierStringToPlanType("default_claude_max_20")).toBe("max20");
		expect(mapTierStringToPlanType("MAX_20")).toBe("max20");
		expect(mapTierStringToPlanType("max20")).toBe("max20");
	});

	it("maps max_5 variants", () => {
		expect(mapTierStringToPlanType("default_claude_max_5x")).toBe("max5");
		expect(mapTierStringToPlanType("MAX_5")).toBe("max5");
		expect(mapTierStringToPlanType("max5")).toBe("max5");
	});

	it("maps pro/standard", () => {
		expect(mapTierStringToPlanType("pro")).toBe("pro");
		expect(mapTierStringToPlanType("standard")).toBe("pro");
		expect(mapTierStringToPlanType("Pro")).toBe("pro");
	});

	it("returns null for unknown tier", () => {
		expect(mapTierStringToPlanType("enterprise")).toBeNull();
		expect(mapTierStringToPlanType("free")).toBeNull();
		expect(mapTierStringToPlanType("")).toBeNull();
	});
});

describe("formatBarGraph", () => {
	it("renders 0% as all empty", () => {
		const result = formatBarGraph(0);
		expect(result).toBe(
			"[\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591\u2591] 0%",
		);
	});

	it("renders 100% as all filled", () => {
		const result = formatBarGraph(100);
		expect(result).toBe(
			"[\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588\u2588] 100%",
		);
	});

	it("renders 50% as half filled", () => {
		const result = formatBarGraph(50);
		expect(result).toContain("50%");
		expect(result.match(/\u2588/g)?.length).toBe(10);
		expect(result.match(/\u2591/g)?.length).toBe(10);
	});

	it("clamps negative percentage to 0", () => {
		const result = formatBarGraph(-10);
		expect(result).toContain("0%");
	});

	it("clamps percentage over 100", () => {
		const result = formatBarGraph(150);
		expect(result).toContain("100%");
	});

	it("supports custom width", () => {
		const result = formatBarGraph(50, 10);
		expect(result.match(/\u2588/g)?.length).toBe(5);
		expect(result.match(/\u2591/g)?.length).toBe(5);
	});
});

describe("formatPaceForecast", () => {
	it("returns empty for null minutes", () => {
		expect(formatPaceForecast(null, "Session")).toBe("");
	});

	it("returns LIMIT HIT for 0 minutes", () => {
		expect(formatPaceForecast(0, "Session")).toBe("Session: LIMIT HIT");
	});

	it("returns <1m for fractional minutes", () => {
		expect(formatPaceForecast(0.5, "Session")).toBe(
			"Session: <1m at current pace",
		);
	});

	it("formats minutes under 60", () => {
		expect(formatPaceForecast(45, "Session")).toBe(
			"Session: ~45m at current pace",
		);
	});

	it("formats hours and minutes", () => {
		expect(formatPaceForecast(135, "Weekly")).toBe(
			"Weekly: ~2h 15m at current pace",
		);
	});
});
