/**
 * Adversarial tests for auth/polling/cache staleness bug
 * Generated by /challenge on 2026-03-23
 *
 * Tests target the 4 files: usageApi.ts, pollingTimer.ts, usageCache.ts, statusBar.ts
 * Focus: auth failure chain, cache freshness lies, polling recovery gaps
 */

import { getStaleness } from "../src/api/usageCache";
import { PollingTimer } from "../src/api/pollingTimer";

// ── getStaleness boundary tests ──

describe("getStaleness", () => {
	beforeEach(() => {
		jest.useFakeTimers();
		jest.setSystemTime(new Date("2026-03-23T12:00:00.000Z"));
	});

	afterEach(() => {
		jest.useRealTimers();
	});

	test("returns 'normal' when fetchedAt is null (no API data)", () => {
		// BUG: null means "never fetched" but returns "normal" (same as 30-60m old)
		// This test documents the current behavior; fix should return "unavailable"
		expect(getStaleness(null)).toBe("normal");
	});

	test("returns 'fresh' for data fetched 0ms ago", () => {
		expect(getStaleness(new Date())).toBe("fresh");
	});

	test("returns 'fresh' at exactly 29m59s", () => {
		const fetchedAt = new Date(Date.now() - 29 * 60_000 - 59_000);
		expect(getStaleness(fetchedAt)).toBe("fresh");
	});

	test("returns 'normal' at exactly 30m", () => {
		const fetchedAt = new Date(Date.now() - 30 * 60_000);
		expect(getStaleness(fetchedAt)).toBe("normal");
	});

	test("returns 'dim' at exactly 60m", () => {
		const fetchedAt = new Date(Date.now() - 60 * 60_000);
		expect(getStaleness(fetchedAt)).toBe("dim");
	});

	test("returns 'stale' at exactly 120m", () => {
		const fetchedAt = new Date(Date.now() - 120 * 60_000);
		expect(getStaleness(fetchedAt)).toBe("stale");
	});

	test("returns 'critical' at exactly 240m", () => {
		const fetchedAt = new Date(Date.now() - 240 * 60_000);
		expect(getStaleness(fetchedAt)).toBe("critical");
	});

	test("returns 'critical' at 160m (the reported bug scenario)", () => {
		const fetchedAt = new Date(Date.now() - 160 * 60_000);
		// 160m is between 120m (stale) and 240m (critical)
		expect(getStaleness(fetchedAt)).toBe("stale");
	});

	test("BREAKER: backward clock jump produces negative age, reads as fresh", () => {
		// fetchedAt is 2 hours in the FUTURE (clock jumped backward after fetch)
		const fetchedAt = new Date(Date.now() + 2 * 60 * 60_000);
		const result = getStaleness(fetchedAt);
		// BUG: negative ageMs passes all "< threshold" checks, returns "fresh"
		// This should return "stale" or "unknown", not "fresh"
		expect(result).toBe("fresh"); // documents the bug
	});

	test("BREAKER: Date far in the past returns critical", () => {
		const fetchedAt = new Date("2020-01-01T00:00:00.000Z");
		expect(getStaleness(fetchedAt)).toBe("critical");
	});
});

// ── PollingTimer tests ──

describe("PollingTimer", () => {
	let fetchFn: jest.Mock;
	let onData: jest.Mock;
	let onError: jest.Mock;
	let mockLogger: any;
	let timer: PollingTimer;

	beforeEach(() => {
		jest.useFakeTimers();
		fetchFn = jest.fn();
		onData = jest.fn();
		onError = jest.fn();
		mockLogger = {
			info: jest.fn(),
			warn: jest.fn(),
			error: jest.fn(),
		};
		timer = new PollingTimer(fetchFn, onData, onError, mockLogger);
	});

	afterEach(() => {
		timer.dispose();
		jest.useRealTimers();
	});

	test("first tick fires after 5s initial interval", () => {
		fetchFn.mockResolvedValue({ fiveHour: null, fetchedAt: new Date() });
		timer.start();

		expect(fetchFn).not.toHaveBeenCalled();
		jest.advanceTimersByTime(5000);
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});

	test("schedules 120s interval after success", async () => {
		const apiData = { fiveHour: null, fetchedAt: new Date() };
		fetchFn.mockResolvedValue(apiData);
		timer.start();

		// First tick at 5s
		jest.advanceTimersByTime(5000);
		await Promise.resolve(); // flush microtasks

		expect(onData).toHaveBeenCalledWith(apiData);

		// Next tick should be at 120s
		fetchFn.mockClear();
		jest.advanceTimersByTime(119_999);
		expect(fetchFn).not.toHaveBeenCalled();
		jest.advanceTimersByTime(1);
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});

	test("exponential backoff on failure: 30s, 60s, 120s, 240s, 300s cap", async () => {
		fetchFn.mockResolvedValue(null);
		timer.start();

		const expectedBackoffs = [30_000, 60_000, 120_000, 240_000, 300_000];

		// First tick at 5s
		jest.advanceTimersByTime(5000);
		await Promise.resolve();
		expect(onError).toHaveBeenCalledTimes(1);

		for (const backoff of expectedBackoffs) {
			fetchFn.mockClear();
			onError.mockClear();

			jest.advanceTimersByTime(backoff - 1);
			expect(fetchFn).not.toHaveBeenCalled();
			jest.advanceTimersByTime(1);
			await Promise.resolve();
			expect(fetchFn).toHaveBeenCalledTimes(1);
		}
	});

	test("BUG: no circuit breaker after many failures", async () => {
		fetchFn.mockResolvedValue(null);
		timer.start();

		// Simulate 20 consecutive failures
		jest.advanceTimersByTime(5000);
		await Promise.resolve();

		for (let i = 0; i < 19; i++) {
			jest.advanceTimersByTime(300_000); // max backoff
			await Promise.resolve();
		}

		// After 20 failures, still retrying (no circuit breaker)
		// BUG: should stop or notify user after N failures
		expect(onError).toHaveBeenCalledTimes(20);
		fetchFn.mockClear();
		jest.advanceTimersByTime(300_000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(1); // still retrying
	});

	test("BUG: forceRefresh is no-op when tick is in-flight", async () => {
		// Make fetchFn hang (never resolve)
		let resolveFetch: (v: any) => void;
		fetchFn.mockReturnValue(
			new Promise((resolve) => {
				resolveFetch = resolve;
			}),
		);

		timer.start();
		jest.advanceTimersByTime(5000); // triggers tick, but it hangs

		// User clicks refresh while tick is in-flight
		const forcePromise = timer.forceRefresh();
		await forcePromise;

		// BUG: forceRefresh returned without doing anything
		// fetchFn was only called once (the original tick), not twice
		expect(fetchFn).toHaveBeenCalledTimes(1);

		// Clean up the hanging promise
		resolveFetch!(null);
		await Promise.resolve();
	});

	test("success resets consecutiveFailures", async () => {
		// 3 failures, then success, then failure
		fetchFn
			.mockResolvedValueOnce(null)
			.mockResolvedValueOnce(null)
			.mockResolvedValueOnce(null)
			.mockResolvedValueOnce({ fiveHour: null, fetchedAt: new Date() })
			.mockResolvedValueOnce(null);

		timer.start();

		// 3 failures
		jest.advanceTimersByTime(5000);
		await Promise.resolve();
		jest.advanceTimersByTime(30_000);
		await Promise.resolve();
		jest.advanceTimersByTime(60_000);
		await Promise.resolve();

		// Success
		jest.advanceTimersByTime(120_000);
		await Promise.resolve();
		expect(onData).toHaveBeenCalledTimes(1);

		// Next failure should be back to 30s backoff (not 240s)
		onError.mockClear();
		jest.advanceTimersByTime(120_000);
		await Promise.resolve();

		// Verify the next retry is 30s (reset), not 240s (continued)
		fetchFn.mockClear();
		jest.advanceTimersByTime(30_000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});

	test("onData callback error does not kill timer", async () => {
		fetchFn.mockResolvedValue({ fiveHour: null, fetchedAt: new Date() });
		onData.mockImplementation(() => {
			throw new Error("callback crashed");
		});

		timer.start();
		jest.advanceTimersByTime(5000);
		await Promise.resolve();

		expect(mockLogger.error).toHaveBeenCalled();

		// Timer should schedule next tick despite callback error
		fetchFn.mockClear();
		jest.advanceTimersByTime(120_000);
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});

	test("stop() prevents further ticks", async () => {
		fetchFn.mockResolvedValue({ fiveHour: null, fetchedAt: new Date() });
		timer.start();

		jest.advanceTimersByTime(5000);
		await Promise.resolve();
		expect(fetchFn).toHaveBeenCalledTimes(1);

		timer.stop();
		fetchFn.mockClear();

		jest.advanceTimersByTime(120_000);
		expect(fetchFn).not.toHaveBeenCalled();
	});

	test("start() is idempotent", () => {
		timer.start();
		timer.start();
		timer.start();

		jest.advanceTimersByTime(5000);
		expect(fetchFn).toHaveBeenCalledTimes(1);
	});
});

// ── Cache readCache freshness lie test ──
// Note: readCache requires fs mocking which is more complex.
// These tests document the expected behavior for the fetchedAt fallback bug.

describe("Cache fetchedAt fallback behavior (documented bugs)", () => {
	test("DESIGN DOC: missing fetchedAt should NOT default to new Date()", () => {
		// When usageCache.readCache encounters missing fetchedAt:
		//   typeof parsed.apiUsage.fetchedAt === "string" -> false (undefined)
		//   Falls to else branch: parsed.apiUsage.fetchedAt = new Date()
		//
		// This makes stale/corrupt cache data appear fresh.
		// Fix: return null or set to a sentinel value that getStaleness treats as stale.
		//
		// Verifiable by checking: if fetchedAt was set to new Date(),
		// getStaleness would return "fresh" for data that could be hours old.
		const fakeNow = new Date("2026-03-23T12:00:00.000Z");
		expect(getStaleness(fakeNow)).toBe("fresh");
		// ^ This is what happens with the fallback. The correct result
		// for missing fetchedAt should be "stale" or "critical", not "fresh".
	});

	test("DESIGN DOC: numeric fetchedAt (from old extension version) falls to default", () => {
		// If an older version stored fetchedAt as a Unix timestamp number,
		// typeof check fails (number !== "string"), falls to else: new Date()
		// Data appears fresh regardless of actual age.
		// Fix: also handle typeof === "number" -> new Date(parsed.apiUsage.fetchedAt)
	});
});
