name: CI
on: [push, pull_request]
jobs:
  ci:
    uses: voyagi/.github-workflows/.github/workflows/node-ci.yml@a79dfb7c9a8147039f884d6478243d435b81d2b7 # main
    with:
      run-knip: false
    secrets: inherit
