name: Mirror to Codeberg

on:
  push:
    branches: [main, master]

jobs:
  mirror:
    uses: voyagi/.github-workflows/.github/workflows/mirror-codeberg.yml@a79dfb7c9a8147039f884d6478243d435b81d2b7 # main
    secrets:
      CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
